services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: always
    environment:
      LOG_LEVEL: info
      TZ: Asia/Shanghai
      TEST_URL: https://www.baidu.com
    ports:
      - "8191:8191"
    networks:
      - cqps-net

  cqps:
    build:
      context: .
      dockerfile: Dockerfile
    image: cq-picsearcher-bot:local
    restart: always
    depends_on:
      - flaresolverr
    volumes:
      - ./data:/app/data
      - ./config.jsonc:/app/config.jsonc
    networks:
      - cqps-net

networks:
  cqps-net:
    driver: bridge
